version: 2

project_name: cubectl
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: main.go
    binary: cubectl
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
      - 386
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
release:
  prerelease: auto
brews:
  - name: cubectl
    repository:
      owner: y-hatano-github
      name: homebrew-tap
    directory: Formula
    homepage: "https://github.com/y-hatano-github/cubectl"
    description: "cubectl controls cube instead of Kubernetes clusters."
    license: "MIT"
    test: |
      system "#{bin}/cubectl --help"
    install: |
      bin.install "cubectl"
